name: Generate documentation

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'


jobs:
  generate-doc:
    name: Build and publish Eudract documentation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.x"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[dev]
    - name: Generate documentation
      run: |
        cp CHANGELOG.md docs/source/changelog.md
        cd docs
        make html
    - uses: actions/upload-artifact@v3
      with:
        name: docs
        path: docs/build/html
  publish-doc:
    name: commit doc on gh-pages branch
    runs-on: ubuntu-latest
    needs: generate-doc
    steps:
      - uses: actions/checkout@v3
        with:
         ref: gh-pages
      - uses: actions/download-artifact@v3
        with:
          name: docs
          path: docs
      - name: add and push
        run: |
          tag_version=${{ github.ref_name}}
          tag_version="${tag_version:1}"
          echo "building doc for $tag_version"
          rm -f -R $tag_version
          mv docs $tag_version
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"
          git add --all $tag_version
          git commit -m "new doc for $tag_version"
          git push